### ISSUE TITLE
Typo in include

### ISSUE THREAD

**Issue by KrisThielemans** [gschramm/parallelproj#16]
https://github.com/gschramm/parallelproj/blob/master/c/include/parallelproj_c.h#L284
Has a ; at the end. Should be a comma?

**Comment by gschramm** [comment]
Thanks for spotting this typo Kris. It is fixed in version 1.0.1 
https://github.com/gschramm/parallelproj/releases/tag/v1.0.1
https://github.com/gschramm/parallelproj/compare/v1.0.0...v1.0.1

On top of that, the cuda device kernels have been moved to a separate file such that they can be directly used by cupy (to run complete recons directly on the GPU without host-GPU transfers).
Build process and API have not been changed.
