### ISSUE TITLE
document that the forward projector accumulates

### ISSUE THREAD

**Issue by KrisThielemans** [gschramm/parallelproj#7]
Admittedly, I didn't read the documentation... But it surprised me that forward projection adds to the existing data (but it's fine, as long as we know)

**Comment by gschramm** [comment]
Well spotted, this was actually a point where the C/OpenMP and CUDA implementation behaved differently  - which was corrected.
Now in both implementations the projection arrays are initialized with 0s before the fwd projection is done.
Initializing with 0s makes more sense, since in CUDA it avoids unnecessary memory transfer, and the overhead in the
OpenMP implementation should be negligible.

The documentation is also updated (mentioning that in the back projection values are added to the existing array).

**Comment by KrisThielemans** [comment]
ok. I guess we could skip the fill() in STIR then...

**Comment by gschramm** [comment]
definitely. sorry for the inconvenience.
